version: '3'
services:
  prolog:
    image: ubuntu1604py36
    container_name: prolog
  tests:
    image: ubuntu1604py36
    container_name: tests
    depends_on:
      - "prolog"
    command: ["./wait-for-prolog-and-test.sh"]
